# Generated by Django 5.1.4 on 2025-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_github_url_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.IntegerField(default=0),
        ),
    ]
