# Generated by Django 5.1.4 on 2025-01-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
