# Generated by Django 5.1.4 on 2025-01-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.TextField(null=True),
        ),
    ]
