# Generated by Django 5.1.4 on 2025-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tiktok',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
