# Generated by Django 5.1.4 on 2025-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_instagram_project_project_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_assigned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
