# Generated by Django 5.1.4 on 2025-01-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_team_created_by_alter_team_project_assigned_and_more'),
        ('projects', '0012_alter_project_project_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
