# Generated by Django 5.1.4 on 2025-01-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_team_assigned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
    ]
