# Generated by Django 5.1.4 on 2025-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.IntegerField(choices=[(0, 'Planeación'), (1, 'Desarrollo'), (2, 'Pruebas'), (3, 'Presentación'), (4, 'Concluido')], default=0),
        ),
    ]
