# Generated by Django 5.1.4 on 2025-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_project_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.IntegerField(choices=[(1, 'Planeación'), (2, 'Desarrollo'), (3, 'Pruebas'), (4, 'Presentación'), (5, 'Concluido')], default=1),
        ),
    ]
