# Generated by Django 5.1.4 on 2025-01-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
