# Generated by Django 5.1.4 on 2025-01-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_team_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
