# Generated by Django 5.1.4 on 2025-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_team_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='l2wfkkgt83', max_length=10, unique=True),
        ),
    ]
