# Generated by Django 5.1.4 on 2025-01-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_team_team_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='jx7gn1yrj2', max_length=10, unique=True),
        ),
    ]
