# Generated by Django 5.1.4 on 2025-01-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_team_name_team_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='duz3nbssit', max_length=10, unique=True),
        ),
    ]
