# Generated by Django 5.1.4 on 2025-01-29 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_team_team_code'),
        ('projects', '0012_alter_project_project_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='kokktytkt4', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='accounts.team'),
        ),
    ]
