# Generated by Django 5.1.4 on 2025-01-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_team_created_by_alter_team_project_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='1rxxo9akqr', max_length=10, unique=True),
        ),
    ]
