# Generated by Django 5.1.4 on 2025-01-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_team_created_by_alter_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='zk8y4mq2sb', max_length=10, unique=True),
        ),
    ]
