# Generated by Django 5.1.4 on 2025-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_is_tutor_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='nrxpndvtbl', max_length=10, unique=True),
        ),
    ]
