# Generated by Django 5.1.4 on 2025-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_team_team_code_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='zn2yom5jfq', max_length=10, unique=True),
        ),
    ]
