# Generated by Django 5.1.4 on 2025-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='2jutrr6jl4', max_length=10, unique=True),
        ),
    ]
